#KPAH license store
#Tue Apr 28 21:10:24 GMT+07:00 2026
license.0.app_build=
license.0.bound_at=0
license.0.code=KPAH-ZDXG-FNY9-HY2U-VBAG-44Y4
license.0.created_at=1777385424246
license.0.days=7
license.0.device_name=
license.0.expires_at=1777990224246
license.0.last_seen_at=0
license.0.machine_id=
license.0.machine_user=
license.0.note=
license.0.remote_address=
license.0.status=active
license.1.app_build=
license.1.bound_at=0
license.1.code=KPAH-XJVW-F3CD-UBAQ-EDTJ-X2YQ
license.1.created_at=1777359059545
license.1.days=7
license.1.device_name=
license.1.expires_at=1777963859545
license.1.last_seen_at=0
license.1.machine_id=
license.1.machine_user=
license.1.note=
license.1.remote_address=
license.1.status=active
license.10.app_build=
license.10.bound_at=0
license.10.code=KPAH-94MS-XR9A-L8KQ-5J73-RAQC
license.10.created_at=1776779234872
license.10.days=7
license.10.device_name=
license.10.expires_at=1777384034872
license.10.last_seen_at=0
license.10.machine_id=
license.10.machine_user=
license.10.note=
license.10.remote_address=
license.10.status=active
license.11.app_build=
license.11.bound_at=0
license.11.code=KPAH-SZDM-SR5F-NJCD-PBKF-NGYU
license.11.created_at=1776779203791
license.11.days=7
license.11.device_name=
license.11.expires_at=1777384003791
license.11.last_seen_at=0
license.11.machine_id=
license.11.machine_user=
license.11.note=
license.11.remote_address=
license.11.status=active
license.2.app_build=desktop-portable
license.2.bound_at=1776780274722
license.2.code=KPAH-JLP7-KVDQ-NV6E-7NDS-UAGR
license.2.created_at=1776780271144
license.2.days=7
license.2.device_name=HOME-PC
license.2.expires_at=1777385071144
license.2.last_seen_at=1776867550606
license.2.machine_id=KPAH-E419-CAC0-706B-D76C-3952-383D
license.2.machine_user=Administrator
license.2.note=
license.2.remote_address=/163.61.183.129
license.2.status=active
license.3.app_build=smoke-test
license.3.bound_at=1776779928843
license.3.code=KPAH-654J-HLHE-QTKE-WTHW-RC2N
license.3.created_at=1776779927800
license.3.days=2
license.3.device_name=SMOKE-PC
license.3.expires_at=1776952727800
license.3.last_seen_at=1776779928843
license.3.machine_id=TEST-MACHINE-A
license.3.machine_user=admin
license.3.note=curl-bind-final
license.3.remote_address=/127.0.0.1
license.3.status=active
license.4.app_build=
license.4.bound_at=0
license.4.code=KPAH-JMRN-PGDY-ZU8E-E4SS-EEJJ
license.4.created_at=1776779910528
license.4.days=7
license.4.device_name=
license.4.expires_at=1777384710528
license.4.last_seen_at=0
license.4.machine_id=
license.4.machine_user=
license.4.note=final smoke
license.4.remote_address=
license.4.status=active
license.5.app_build=
license.5.bound_at=0
license.5.code=KPAH-Z79Z-YWCQ-22G8-QPFJ-C9FE
license.5.created_at=1776779907050
license.5.days=3
license.5.device_name=
license.5.expires_at=1777039107050
license.5.last_seen_at=0
license.5.machine_id=
license.5.machine_user=
license.5.note=direct-header-test
license.5.remote_address=
license.5.status=active
license.6.app_build=smoke-test
license.6.bound_at=1776779718161
license.6.code=KPAH-72GH-YJPW-2TH7-UKCJ-GMJ7
license.6.created_at=1776779717581
license.6.days=7
license.6.device_name=SMOKE-PC
license.6.expires_at=1777384517581
license.6.last_seen_at=1776779718161
license.6.machine_id=TEST-MACHINE-A
license.6.machine_user=admin
license.6.note=
license.6.remote_address=/127.0.0.1
license.6.status=active
license.7.app_build=smoke-test
license.7.bound_at=1776779354402
license.7.code=KPAH-37M9-Y5GD-NENA-DF6G-GUT3
license.7.created_at=1776779353759
license.7.days=7
license.7.device_name=SMOKE-PC
license.7.expires_at=1777384153759
license.7.last_seen_at=1776779354444
license.7.machine_id=TEST-MACHINE-A
license.7.machine_user=admin
license.7.note=
license.7.remote_address=/127.0.0.1
license.7.status=active
license.8.app_build=desktop-portable
license.8.bound_at=1776779343887
license.8.code=KPAH-3D8N-FXA9-APRL-AAZ5-BABC
license.8.created_at=1776779340628
license.8.days=7
license.8.device_name=DESKTOP-R4C0BMD
license.8.expires_at=1777384140628
license.8.last_seen_at=1776779379644
license.8.machine_id=KPAH-AF7E-6577-2842-5BFE-86BC-0D03
license.8.machine_user=HOANG
license.8.note=
license.8.remote_address=/14.237.93.60
license.8.status=active
license.9.app_build=
license.9.bound_at=0
license.9.code=KPAH-4TXP-NPNL-YK2T-6856-AB2X
license.9.created_at=1776779239597
license.9.days=5
license.9.device_name=
license.9.expires_at=1777211239597
license.9.last_seen_at=0
license.9.machine_id=
license.9.machine_user=
license.9.note=cli smoke
license.9.remote_address=
license.9.status=active
license.count=12
